name: Bug Report
description: Report a bug
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Inform us the behavior of the bug.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: What is your `Minecraft` version?
      options:
        - 1.18.2 (Default)
    validations:
      required: true
  - type: input
    id: create-version
    attributes:
      label: Create Version
      description: What is your `Create` version?
      placeholder: E.g., 0.5.0.g-836
    validations:
      required: true
  - type: input
    id: create-encases-version
    attributes:
      label: "Create: Encases Version"
      description: "What is your `Create: Encases` version?"
      placeholder: E.g., 1.0.0
    validations:
      required: true
  - type: input
    id: crash-log
    attributes:
      label: Crash Log
      description: Please use a pastebin service(e.g., https://paste.ubuntu.com) to hold your log and paste the link below.
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else?
      render: markdown
